import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import { SidebarProvider } from '@/components/ui/sidebar'
import AppSidebar from '@/components/SideBar/app-sidebar'
import { Toaster } from '@/components/ui/toaster'
import NavBar from '@/components/NavBar/NavBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SidebarProvider>
            <main className="flex w-full">
              <AppSidebar />
              <div className="mx-auto">
                <NavBar />
                <div className="container mx-auto px-5">
                  {children}
                </div>
              </div>
            </main>
          </SidebarProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
