import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import AppSidebar from '@/components/SideBar/app-sidebar'
import { Toaster } from '@/components/ui/toaster'
import NavBar from '@/components/NavBar/NavBar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <main className="flex w-full">
            <AppSidebar />
            <div className="w-full">
              <NavBar />
              <div className="cont">{children}</div>
            </div>
          </main>
        </Providers>
        <Toaster />
      </body>
    </html>
  )
}
